- name: Add key for NodeJS repository
  sudo: yes
  apt_key: url=https://deb.nodesource.com/gpgkey/nodesource.gpg.key state=present

- name: Add repository for NodeJS
  sudo: yes
  apt_repository: repo='deb https://deb.nodesource.com/node_4.x {{ ansible_distribution_release }} main' state=present

- name: Install NodeJS
  sudo: yes
  apt: pkg=nodejs state=latest
